- core/src/data_structure/signed_transaction.rs
- core/src/data_structure/state_object.rs
- core/src/data_structure/state_update.rs
- core/src/data_structure/transaction.rs
changed visibility of attributes.
> Add builder functinos

- .travis.yml
- Cargo.lock
- core/src/data_structure.rs
- core/src/data_structure/block.rs
- core/src/data_structure/included_transaction.rs
- core/src/data_structure/signed_transaction.rs
- core/src/data_structure/state_object.rs
- core/src/data_structure/state_update.rs
- core/src/data_structure/transaction.rs
- core/src/process.rs
- core/src/process/block_generator.rs
- operator/Cargo.toml
- operator/src/error.rs
- operator/src/lib.rs
- operator/src/server.rs
- use more strict settings. Linter warnings. should fail CI.
- fix code
> Fix options for clippy and code

- Cargo.lock
- Cargo.toml
- sum_merkle_tree/Cargo.toml
- sum_merkle_tree/src/lib.rs
Close #11 
reference architecture: https://github.com/plasma-group/pigi/blob/master/packages/utils/src/sum-tree.ts
> Add sum_merkle_tree #11

- .travis.yml
* remove `.NDK` from cache folder
* deploy job runs only master branch
> remove .NDK from cache

- core/src/data_structure/error.rs
- core/src/data_structure/state_object.rs
- core/src/data_structure/state_update.rs
- core/src/data_structure/transaction.rs
avoid `unwrap`.
https://users.rust-lang.org/t/validating-multiple-options-at-once/3902/2
> Clean decoder

- Cargo.lock
- core/Cargo.toml
- core/src/data_structure/error.rs
- core/src/data_structure/state_update.rs
- core/src/data_structure/transaction.rs
- core/src/lib.rs
- core/src/state.rs
- core/src/state/state_db.rs
- core/src/state/state_manager.rs
- core/src/state_manager.rs
Add minimal StateManager implementation and spec.
Close #44
> Add state manager

- client/src/state/state_db.rs
- client/src/state/state_manager.rs
- core/src/data_structure/state_update.rs
Thanks, @satellitex !
We should use borrowing rather than reference.
> Remove unnecessary clone

- Cargo.lock
- sum_merkle_tree/Cargo.toml
- sum_merkle_tree/src/index.rs
- sum_merkle_tree/src/lib.rs
Make 'index' of Merkle tree more general using type parameter.
> Add Index trait for u64 #60

- client/src/error.rs
- client/src/lib.rs
- client/src/state/state_manager.rs
- client/src/sync.rs
- client/src/sync/sync_db.rs
- client/src/sync/sync_manager.rs
- core/src/data_structure.rs
- core/src/data_structure/state_query.rs
- core/src/types.rs
- db/src/impls/kvs/leveldb.rs
- db/src/impls/kvs/memory.rs
- db/src/traits/kvs.rs
depends on #36 and #77 
Close #56
> Add minmal SyncManager #56

- Cargo.lock
- client/Cargo.toml
- client/src/error.rs
- client/src/lib.rs
- client/src/plasma_rpc.rs
- core/src/data_structure/state_query.rs
Added JSON RPC client over HTTP protocol. Right now I added three APIs and wrote specs for each.
Close #9 
https://github.com/satellitex/test-substrate-rpc
> Add minimal json rpc client #9

- client/src/plasma_rpc.rs
- client/src/state/state_manager.rs
- client/src/sync/sync_manager.rs
- core/src/data_structure/state_query.rs
Add `sync` method in SyncManager. It called when new block submitted event happened.
Close #85
> Sync state

- Cargo.lock
- Cargo.toml
- wasm/.gitignore
- wasm/Cargo.toml
- wasm/README.md
- wasm/src/lib.rs
- wasm/tests/web.rs
Need discussion of how to publish Wasm and npm package. Publishing package with CI on separate PR.
> Add wasm crate

- client/src/sync/sync_manager.rs
> Remove unnecessary SyncManagerTrait #98

- Cargo.lock
- event-watcher/Cargo.toml
- event-watcher/src/event_db.rs
- event-watcher/src/lib.rs
- event-watcher/src/main.rs
Use KVS to implement EventDB. #99 
TODO:
- error handling 
- better to think about error propagation?
> Use KVS inside EventDB

- client/src/sync/sync_db.rs
- client/src/sync/sync_manager.rs
This is refactoring following #105
> Remove SyncDbTrait #105

- Cargo.lock
- client/src/plasma_rpc.rs
- client/src/state/state_db.rs
- client/src/state/state_manager.rs
- client/src/sync/sync_db.rs
- core/Cargo.toml
- core/src/data_structure.rs
- core/src/data_structure/abi.rs
- core/src/data_structure/range.rs
- core/src/data_structure/state_object.rs
- core/src/data_structure/state_query.rs
- core/src/data_structure/state_update.rs
- core/src/data_structure/transaction.rs
- operator/src/block/block_db.rs
- operator/src/context.rs
- operator/src/rpc/plasmarpcimpl.rs
- predicate-plugins/src/ownership.rs
- wasm/src/lib.rs
- Add range to core.
- Update data structures.
Close #80 #106
> Follow the latest data structures #106 #80

- event-watcher/src/event_watcher.rs
> Tweak variable/method name

- client/src/error.rs
- core/src/data_structure/error.rs
- operator/src/error.rs
Fix CI build error.
Close #112
> Fix warnnings #112

- .travis.yml
CI of master branch is failing, and it's confusing now. Stop deploying docs and fix it later.
https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/67
> Stop deploy doc because of failing #67

- Cargo.lock
- core/src/lib.rs
- core/src/ovm.rs
- core/src/ovm/decider.rs
- core/src/ovm/quantifier.rs
- core/src/ovm/types.rs
- predicate-plugins/Cargo.toml
- predicate-plugins/src/deciders.rs
- predicate-plugins/src/deciders/preimage_exists_decider.rs
- predicate-plugins/src/lib.rs
Close #133 
I added basic struct for OVM, and wrote `PreimageExistsDecider` as an example.
> Add ovm data structure #133

- contract-wrapper/src/error.rs
- ovm/src/deciders/and_decider.rs
- ovm/src/deciders/for_all_such_that_decider.rs
- ovm/src/deciders/has_lower_nonce.rs
- ovm/src/deciders/not_decider.rs
- ovm/src/deciders/preimage_exists_decider.rs
- ovm/src/deciders/signed_by_decider.rs
- ovm/src/lib.rs
- ovm/src/property_executor.rs
- ovm/src/quantifiers/integer_quantifiers.rs
- ovm/src/quantifiers/signed_by_quantifier.rs
- ovm/src/types.rs
- ovm/src/types/core.rs
- ovm/src/types/inputs.rs
> Modify QuantifierResult to support Property #148

- db/src/impls/kvs/leveldb.rs
- db/src/impls/kvs/memory.rs
- db/src/impls/rangedb.rs
- db/src/traits/kvs.rs
Add getting bucket method to RangeDb.
This is a part of https://github.com/cryptoeconomicslab/plasma-rust-framework/pull/155.
> Add bucket method to RangeDb

- Cargo.lock
- event-watcher/Cargo.toml
- event-watcher/src/event_watcher.rs
- event-watcher/src/main.rs
This PR closes https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/115 👷
> event-watcher: Decoded params

- Cargo.lock
- core/src/data_structure/range.rs
- core/src/data_structure/transaction.rs
- merkle-interval-tree/src/lib.rs
- ovm/Cargo.toml
- ovm/src/deciders.rs
- ovm/src/deciders/and_decider.rs
- ovm/src/deciders/for_all_such_that_decider.rs
- ovm/src/deciders/has_lower_nonce.rs
- ovm/src/deciders/included_in_interval_tree_at_block_decider.rs
- ovm/src/deciders/not_decider.rs
- ovm/src/deciders/or_decider.rs
- ovm/src/deciders/preimage_exists_decider.rs
- ovm/src/deciders/signed_by_decider.rs
- ovm/src/error.rs
- ovm/src/lib.rs
- ovm/src/property_executor.rs
- ovm/src/quantifiers.rs
- ovm/src/quantifiers/block_range_quantifier.rs
- ovm/src/statements.rs
- ovm/src/statements/plasma.rs
- ovm/src/types.rs
- ovm/src/types/core.rs
- ovm/src/types/decision_value.rs
- ovm/src/types/inputs.rs
- ovm/src/types/witness.rs
- predicate-plugins/src/ownership.rs
> Plasma statement example

- ovm/src/db.rs
- ovm/src/db/hash_preimage_db.rs
- ovm/src/deciders/and_decider.rs
- ovm/src/deciders/for_all_such_that_decider.rs
- ovm/src/deciders/or_decider.rs
- ovm/src/deciders/preimage_exists_decider.rs
- ovm/src/lib.rs
I feel we need discussion. This PR is about what I said in last call.
child of #160
> load witness from database at PreimageExistsDecider #160

- ovm/src/deciders/for_all_such_that_decider.rs
> Fix import Integer

- ovm/src/deciders/and_decider.rs
- ovm/src/deciders/for_all_such_that_decider.rs
- ovm/src/deciders/has_lower_nonce.rs
- ovm/src/deciders/included_in_interval_tree_at_block_decider.rs
- ovm/src/deciders/not_decider.rs
- ovm/src/deciders/or_decider.rs
- ovm/src/deciders/preimage_exists_decider.rs
- ovm/src/deciders/signed_by_decider.rs
- ovm/src/lib.rs
- ovm/src/property_executor.rs
- ovm/src/statements/plasma.rs
- ovm/src/types.rs
- ovm/src/types/core.rs
- ovm/src/types/inputs.rs
>  Remove unnecessary witness argument for Deciders

- clients/Cargo.toml
- core/src/data_structure/state_object.rs
- core/src/data_structure/state_update.rs
- core/src/data_structure/transaction.rs
- db/src/impls/kvs/leveldb.rs
- db/src/impls/kvs/memory.rs
- db/src/impls/rangedb.rs
- db/src/range.rs
- event-watcher/src/event_db.rs
- merkle-interval-tree/src/lib.rs
- ovm/src/deciders/and_decider.rs
- ovm/src/deciders/for_all_such_that_decider.rs
- ovm/src/deciders/or_decider.rs
- ovm/src/deciders/preimage_exists_decider.rs
- ovm/src/deciders/signed_by_decider.rs
- ovm/src/types/core.rs
- ovm/src/types/inputs.rs
> Style for rustfmt

- db/src/impls/kvs/leveldb.rs
- db/src/impls/kvs/memory.rs
- db/src/traits/kvs.rs
Current iter_all don't have limitation.
So the result of this test was 3. It's inconvenient.
```
fn test_iter() {
let core_db = CoreDb::open("test");
let root: Bucket = core_db.root();
let bucket_a: Bucket = root.bucket(&"a".into());
let bucket_b: Bucket = root.bucket(&"b".into());
assert_eq!(bucket_a.put(&"0".into(), &b"value"[..]).is_ok(), true);
assert_eq!(bucket_a.put(&"1".into(), &b"value"[..]).is_ok(), true);
assert_eq!(bucket_b.put(&"0".into(), &b"value"[..]).is_ok(), true);
let result = bucket_a.iter_all(&"".into(), Box::new(move |_k, _v| true));
assert_eq!(result.len(), 2);
}
```
> Fix KeyValueStore.iter_all

- ovm/src/db/message_db.rs
- ovm/src/lib.rs
- ovm/src/statements.rs
- ovm/src/statements/state_channel.rs
Related to #159 
creating state channel exit property.
> Create state channel property

- Cargo.lock
- Cargo.toml
- chamber/Cargo.toml
- chamber/src/lib.rs
- clients/Cargo.toml
- clients/src/state_channel.rs
- db/src/traits/kvs.rs
- ovm/src/db.rs
- ovm/src/db/channel_db.rs
- ovm/src/db/message_db.rs
- ovm/src/db/signed_by_db.rs
- ovm/src/deciders/signed_by_decider.rs
- ovm/src/lib.rs
- ovm/src/property_executor.rs
- ovm/src/quantifiers/signed_by_quantifier.rs
- ovm/src/statements/state_channel.rs
> Add state channel client

- clients/examples/plasma_aggregator.rs
- clients/examples/plasma_client.rs
- clients/src/plasma/plasma_client.rs
- pubsub-messaging/examples/simple_server_and_client.rs
- pubsub-messaging/src/client/client_impl.rs
- pubsub-messaging/src/server/server_impl.rs
> change pubsub endpoint type to String

- ovm/src/db.rs
- ovm/src/db/hash_preimage_db.rs
- ovm/src/db/range_at_block_db.rs
- ovm/src/deciders/and_decider.rs
- ovm/src/deciders/for_all_such_that_decider.rs
- ovm/src/deciders/included_at_block_decider.rs
- ovm/src/deciders/or_decider.rs
- ovm/src/deciders/preimage_exists_decider.rs
- ovm/src/deciders/signed_by_decider.rs
- ovm/src/lib.rs
- ovm/src/quantifiers/block_range_quantifier.rs
- ovm/src/statements/plasma.rs
- ovm/src/types/core.rs
- ovm/src/types/decision_value.rs
- ovm/src/types/witness.rs
The purpose of this PR is simple. ImplicationWitness should be just bytes data, smart contract parses witness as bytes.
> Witness should be bytes #201

- clients/examples/plasma_aggregator.rs
- clients/examples/plasma_client.rs
- clients/examples/plasma_client_cli.rs
- clients/src/plasma/plasma_aggregator.rs
- ovm/src/deciders/ownership_decider.rs
- ovm/src/statements/plasma.rs
- ovm/src/types/state_update.rs
There are some remained tasks, but it's good size PR, and problem was solved.
> Fix verify state transition

- Cargo.lock
- clients/Cargo.toml
- clients/examples/plasma_aggregator.rs
- clients/src/plasma/block_db.rs
- clients/src/plasma/block_manager.rs
- clients/src/plasma/error.rs
- clients/src/plasma/plasma_aggregator.rs
- clients/src/plasma/plasma_block.rs
Add submitting merle root task. This task is invoked every 5 seconds. I used tokio for that.
> Add periodic task to submit merkle root

- clients/examples/plasma_aggregator.rs
- clients/src/plasma/block_manager.rs
- clients/src/plasma/error.rs
- contract-wrapper/CommitmentChain.json
- contract-wrapper/src/commitment_contract_adaptor.rs
- contract-wrapper/src/error.rs
> Succeed to submit merkle root #204

- event-watcher/src/event_watcher.rs
- event-watcher/src/lib.rs
- event-watcher/src/main.rs
child PR of #205 
Update EventWathcer's interface to replace listeners to handler trait.
> Replace EventListener to EventHandler #205

- clients/examples/plasma_client.rs
- clients/examples/plasma_client_cli.rs
- clients/examples/plasma_client_server.rs
- clients/src/plasma/plasma_aggregator.rs
- clients/src/plasma/plasma_client.rs
- ovm/src/deciders/ownership_decider.rs
- ovm/src/statements/plasma.rs
- ovm/src/types/state_update.rs
- ovm/src/types/state_update_list.rs
> Support multiple tokens #218

- clients/examples/plasma_client.rs
- clients/examples/plasma_client_cli.rs
- clients/examples/plasma_client_server.rs
- clients/src/plasma/plasma_client.rs
I added `send_ownership` method and `open_channel` method in `PlasmaClientShell`.
> Add channel on Plasma property

- clients/README.md
- clients/src/plasma/plasma_block.rs
- clients/src/plasma/plasma_client.rs
- merkle-interval-tree/src/double_layered_tree.rs
- merkle-interval-tree/src/lib.rs
- ovm/src/deciders/included_at_block_decider.rs
- ovm/src/quantifiers/block_range_quantifier.rs
- ovm/src/statements/plasma.rs
- ovm/src/types/plasma_data_block.rs
> Fix merklize to use Double Layer Merkle Tree #232

- clients/examples/plasma_client_server.rs
- clients/src/plasma.rs
- clients/src/plasma/plasma_aggregator.rs
- clients/src/plasma/plasma_client.rs
- clients/src/plasma/state_db.rs
- clients/src/plasma/token.rs
- db/src/impls/rangedb.rs
- Fix state db to handle multiple tokens.
- Fix state db put_verified_state_update
- add rangedb test cases.
> Fix state db put

- clients/src/plasma/plasma_client.rs
- ovm/src/db/range_at_block_db.rs
- ovm/src/deciders/included_at_block_decider.rs
- ovm/src/lib.rs
- ovm/src/quantifiers/block_range_quantifier.rs
- ovm/src/statements/plasma.rs
child task of #241 
Close #250
> Add deposit contract address to checkpoint property #250

- clients/examples/plasma_client_server.rs
- clients/src/plasma/plasma_client.rs
- ovm/src/deciders.rs
- ovm/src/deciders/ownership_decider.rs
- ovm/src/deciders/verify_tx_decider.rs
- ovm/src/lib.rs
- ovm/src/property_executor.rs
- ovm/src/quantifiers/property_quantifier.rs
- ovm/src/statements.rs
- ovm/src/statements/plasma.rs
- ovm/src/statements/plasma/offline_swap.rs
- ovm/src/statements/plasma/ownership.rs
- ovm/src/types/state_update.rs
Tests haven't been passed yet.
> Add order and take methods to PlasmaClient

- clients/examples/plasma_client_server.rs
- clients/src/plasma.rs
- clients/src/plasma/plasma_aggregator.rs
- clients/src/plasma/plasma_client.rs
- clients/src/plasma/query.rs
- clients/src/plasma/utils.rs
- ovm/src/deciders/included_at_block_decider.rs
- ovm/src/property_executor.rs
- ovm/src/quantifiers/block_range_quantifier.rs
- ovm/src/statements/plasma/offline_swap.rs
I think we can try connecting Android and client for change APIs.
- Implementing `create_exchange_offer`
- Implementing  `get_exchange_offer`
- Implementing `send_exchange`
- Clean query_balance and query_orders
- Add spec for query_orders
- Add is_aggregator option to PropertyExecuter. https://github.com/cryptoeconomicslab/plasma-rust-framework/pull/254/files#diff-75f1d673bb6af0fcd88dacb75f8e0987R55
> Implement get_exchange_offers at plasma_client_server.rs #241

- clients/examples/plasma_aggregator.rs
- clients/examples/plasma_client.rs
- clients/examples/plasma_client_cli.rs
- clients/examples/plasma_client_server.rs
- clients/src/plasma/plasma_aggregator.rs
- clients/src/plasma/plasma_client.rs
- ovm/src/property_executor.rs
initialize block 0 if state_update list is empty.
> Fix bootstrap of aggregator and client

- Cargo.lock
- clients/Cargo.toml
- merkle-interval-tree/Cargo.toml
- merkle-interval-tree/src/hash.rs
- merkle-interval-tree/src/lib.rs
Clean dependencies of merkle tree.
> Clean merkle tree #266
